services:
  - type: web
    name: cricket-attendance-backend
    env: docker
    rootDir: cricket-attendance-backend
    plan: free
    healthCheckPath: /api/auth/test
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-winter-bonus-anj3me5p.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_iE3FguOUCIN9
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
